### ISSUE TITLE
Change nextjs url/secret config file structure

### ISSUE THREAD

**Issue by pmi** [enonic/lib-nextxp#237]
```[tasklist]
### Tasks
- [ ] enonic/app-nextxp#9
- [ ] enonic/lib-nextxp#238
- [ ] enonic/nextjs-adapter#256
- [ ] https://github.com/enonic/nextxp-demo/issues/653
```
